runtime: java
handlers:
  - url: /.*
    script: this field is required, but ignored
readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 9000
endpoints_api_service:
  name: brandinformerservice.el.r.appspot.com
  rollout_strategy: managed